name:                neural-net
version:             0.1.0.0
github:              "danielholmes/neural-net"
license:             BSD3
author:              "Daniel Holmes"
maintainer:          "daniel@danielholmes.org"
copyright:           "2018 Daniel Holmes"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/danielholmes/neural-net#readme>

dependencies:
  - base >= 4.7 && < 5
  - hspec >= 2.4.7 && < 3
  - matrix >= 0.3.5.0 && < 1
  - vector >= 0.11.0.0 && < 1
  - random >= 1.1 && < 2
  - csv >= 0.1.2 && < 1
  - cmdargs >= 0.10.20 && < 1
  - filepath >= 1.4.1 && < 2
  - text >= 1.2.3.0 && < 2

library:
  source-dirs: src

executables:
  neural-net-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - neural-net

tests:
  neural-net-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - neural-net
